sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t jcchalte/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jcchalte/client-test npm run test -- --coverage
    
after_success: 
  - docker build -t jcchalte/multi-client ./client
  - docker build -t jcchalte/multi-nginx ./nginx
  - docker build -t jcchalte/multi-server ./server
  - docker build -t jcchalte/multi-worker ./worker


deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-768953733553"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY